import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/Layout";
import { useEffect, useState } from "react";
import { Card } from "@/components/Card";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState([]);
  useEffect(() => {
    fetch("/api/products")
      .then((res) => res.json())
      .then((res) => setData(res.items))
      .catch((er) => console.log(er));
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout >
        <section className={styles.grid} >
          {data && data?.map((item: any) => (
            <Card
              key={item?.id}
              title={item?.title}
              price={item?.price}
              image={item?.img}
            />
          ))}
        </section>
      </Layout>
    </>
  );
}
